
baseURL = "https://sunnydongbowen.github.io"

# theme
# 主题
theme = "LoveIt"
# themes directory
# 主题目录
#themesDir = "../.."

# website title
# 网站标题
title = "Bovan"
# 是否使用 git 信息

enableGitInfo = true
defaultContentLanguage = "zh-cn"
